# Generated by Django 3.2.5 on 2021-08-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaires',
            name='q1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='q10',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='q2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='q3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='q4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='q5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='q6',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='q7',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='q8',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='q9',
            field=models.IntegerField(null=True),
        ),
    ]
