# Generated by Django 3.2.5 on 2021-08-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choices_choice_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='sort_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
