# Generated by Django 3.2.5 on 2021-08-13 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210807_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaires',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='surveys',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='is_test',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='surveys',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveys',
            name='welcome_description_text',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='surveys',
            name='welcome_header_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
