# Generated by Django 3.2.5 on 2021-08-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_document_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='model_type',
            field=models.CharField(choices=[('ques', 'Questions'), ('choi', 'Choices')], default='', max_length=4, null=True),
        ),
    ]
